Update Jenkinsfile2

diff --git a/Jenkinsfile2 b/Jenkinsfile2
--- a/Jenkinsfile2
+++ b/Jenkinsfile2
@@ -94,7 +94,49 @@ pipeline {
                 }
             }
         }
+            stage('Create EKS Cluster') {
+    steps {
+        script {
+            sh '''
+            echo "☸ Checking if EKS cluster '${EKS_CLUSTER_NAME}' exists..."
+            if ! eksctl get cluster --region ${AWS_REGION} | grep -q ${EKS_CLUSTER_NAME}; then
+                echo "🚀 Cluster not found — creating new EKS cluster: ${EKS_CLUSTER_NAME}"
 
+                cat <<EOF > eks-cluster.yaml
+apiVersion: eksctl.io/v1alpha5
+kind: ClusterConfig
+
+metadata:
+  name: ${EKS_CLUSTER_NAME}
+  region: ${AWS_REGION}
+  version: "1.29"
+
+vpc:
+  cidr: 172.31.30.22
+
+nodeGroups:
+  - name: ng-app
+    instanceType: t2.medium
+    desiredCapacity: 2
+    minSize: 1
+    maxSize: 3
+    iam:
+      withAddonPolicies:
+        imageBuilder: true
+        autoScaler: true
+        ebs: true
+        albIngress: true
+        cloudWatch: true
+EOF
+
+                eksctl create cluster -f eks-cluster.yaml
+            else
+                echo "✅ EKS cluster '${EKS_CLUSTER_NAME}' already exists. Skipping creation."
+            fi
+            '''
+        }
+    }
+}
         stage('Deploy to EKS Cluster') {
             steps {
                 script {
@@ -111,11 +153,12 @@ pipeline {
                     echo "Deploying application to EKS..."
                     kubectl apply -f deployment.yml
                     kubectl apply -f service.yml
-                    kubectl apply -f ingress.yml
                     kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml 
+                    kubectl apply -f ingress.yml
                     echo "Verifying deployment..."
                     kubectl get pods
                     kubectl get svc
+                    kubectl get ingress
                     '''
                 }
             }
